### ISSUE TITLE
Ranging beacons does not stop after beaconManager.stopRangingBeacons() is called

### ISSUE THREAD

**Issue by HikmatTatariAllone** [davidgyoung/android-beacon-library-reference-kotlin#3]
**Expected behaviour**
Using the Kotlin reference app, tapping on "DISABLE RANGING" / "STOP RANGING" stops ranging beacons.

**Actual behaviour**
It keeps ranging beacons after "DISABLE RANGING" / "STOP RANGING" is tapped.

**Steps to reproduce this behavior**

- Have Bluetooth enabled on the device.
- Launch the app.
- Disable monitoring.
- Disable Bluetooth on the device. The app is still ranging beacons after Bluetooth has been disabled (at least, the system UI shows that Bluetooth is disabled).
- Disable ranging. The app UI shows "Ranging disabled - no beacons detected", but the logs show that the app keeps ranging.

**Mobile device model and OS version**
Google Pixel 6a, Android 13 API 33

**Android Beacon Library version**
2.19.4. I Have also tested to update the version to 2.19.5, but it is the same behaviour

**Logs after  "DISABLE RANGING" / "STOP RANGING" has been tapped**
![Logs showing app still ranging beacons](https://user-images.githubusercontent.com/93531698/224005353-7f423e65-a84b-48c2-9ed8-f56fa9227b83.png)

**Comment by philip-segerfast** [comment]
Please look into this issue.

**Comment by davidgyoung** [comment]
I reproduced this issue and created an issue on the library repo here:

https://github.com/AltBeacon/android-beacon-library/issues/1148

**Comment by davidgyoung** [comment]
Fixed in library version 2.19.6.  This repo has been updated to use that version.
